name: private-hello-cicciosgamino # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
architectures:
  - build-on: amd64
    run-on:  amd64
  - build-on: armhf
    run-on: armhf
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  hello:
    command: hello

parts:
  # node.js logicat-iot code 
  node-build:
    source: .
    plugin: nodejs
    # nodejs-version: "13.14.0"
    nodejs-version: "14.3.0"
    nodejs-package-manager: "npm"
    stage-packages:
      - libatomic1

